# Generated by Django 4.1 on 2022-09-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otprecord',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='TemporaryProfile',
        ),
        migrations.DeleteModel(
            name='OtpRecord',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
