# Generated by Django 4.1 on 2022-09-27 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_chiefprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f37940c-282c-4234-b90a-19f1bc4a2f8f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
