# Generated by Django 4.1 on 2022-09-27 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_chiefprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04bfca74-2200-4866-b892-65763bd79445'), editable=False, primary_key=True, serialize=False),
        ),
    ]
