# Generated by Django 4.1 on 2022-09-27 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_chiefprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('644436ee-24c0-4bb2-aa5c-4cea671f36ac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
