# Generated by Django 4.1 on 2022-09-27 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_chiefprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('efd0dead-9d59-45b4-9b89-17047d422651'), editable=False, primary_key=True, serialize=False),
        ),
    ]
