# Generated by Django 4.1 on 2022-09-27 15:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_chiefprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('77a06a89-569a-4a30-8ced-8681f22964c9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chiefprofile',
            name='password',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
