# Generated by Django 4.1 on 2022-09-27 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_chiefprofile_id_alter_chiefprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b80147e-b7b1-4b77-97b0-cd11bf67cf29'), editable=False, primary_key=True, serialize=False),
        ),
    ]
