# Generated by Django 4.1 on 2022-09-27 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_chiefprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b9e2d45-3c1b-468f-aed0-b073636af1ca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
