# Generated by Django 4.1 on 2022-10-04 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_chiefprofile_id_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7359a547-ddb6-48ea-9450-55b82fab7f45'), editable=False, primary_key=True, serialize=False),
        ),
    ]
