# Generated by Django 4.1 on 2022-10-04 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_chiefprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a456de9-7e8b-4af4-9bd1-5987e89ec8af'), editable=False, primary_key=True, serialize=False),
        ),
    ]
